name: android_app
description: "Pocket Lawyer - Legal AI Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pointycastle: ^3.9.1
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.4+1

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.example
    - assets/images/logo.png